name: CloudCostGuard - Demo CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  cost_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install boto3 dash pandas numpy

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # --------------------------------------------
    # CREATE terraform.tfvars FROM GITHUB SECRETS
    # --------------------------------------------
    - name: Create terraform.tfvars from secrets
      run: |
        cat > costgaurd-infra/terraform.tfvars <<EOF
        ec2_key_name   = "${{ secrets.EC2_KEY_NAME }}"
        db_username    = "${{ secrets.DB_USERNAME }}"
        db_password    = "${{ secrets.DB_PASSWORD }}"
        s3_bucket_name = "${{ secrets.S3_BUCKET_NAME }}"
        EOF

    - name: Terraform Init
      working-directory: costgaurd-infra
      run: terraform init -input=false

    - name: Terraform Plan
      working-directory: costgaurd-infra
      run: terraform plan -out=tfplan.binary -input=false

    - name: Convert plan to JSON
      working-directory: costgaurd-infra
      run: terraform show -json tfplan.binary > plan.json

    - name: Move plan.json to Scanner
      run: mv costgaurd-infra/plan.json cloudcost_scanner/plan.json

    - name: Run Cost Scanner
      working-directory: cloudcost_scanner
      id: scanner
      run: |
        python cost_scanner.py
      continue-on-error: true

    - name: Pipeline Decision
      if: ${{ steps.scanner.outcome == 'failure' }}
      run: |
        echo "❌ Budget exceeded — Deployment halted."
        exit 1

    - name: Deployment Success
      if: ${{ steps.scanner.outcome == 'success' }}
      run: |
        echo "✅ All resources within budget."
        echo "🚀 Deployed to AWS (simulated)."
